[[command]]
trigger = "hello"
response = "Hello {user} 🧉!"

[[command]]
trigger = "burstball"
response = "Laugh at Tom falling when his gym ball burst: https://clips.twitch.tv/TriangularAgreeableYogurtSmoocherZ-4Po_zRXgTbfuKF1y 🤣"

[[command]]
trigger = "lurk"
response = "Lurk long and prosper {user} 🖖"

[[command]]
trigger = "sounds"
response = "Find out more about the sound system and add your own sounds at: https://github.com/tombh/tombh_twitch_bot/blob/main/docs/SOUNDS.md"
