[[command]]
trigger = ["hello", "hi"]
response = "Hello {user} 🧉!"

[[command]]
trigger = ["commands", "cmds", "list"]
response = "All our commands can be found here: https://github.com/tombh/tombh_twitch_bot/blob/main/docs/commands.md"

[[command]]
trigger = ["burstball"]
response = "Laugh at Tom falling when his gym ball burst: https://clips.twitch.tv/TriangularAgreeableYogurtSmoocherZ-4Po_zRXgTbfuKF1y 🤣"

[[command]]
trigger = ["lurk"]
response = "Lurk long and prosper {user} 🖖"

[[command]]
trigger = ["part", "farewell", "bye"]
response = "Goodbye {user} 🙇"

[[command]]
trigger = ["unlurk"]
response = "{user} jumped out of the bushes!"

[[command]]
trigger = ["sounds"]
response = "Find out more about the sound system and add your own sounds at: https://github.com/tombh/tombh_twitch_bot/blob/main/docs/SOUNDS.md"

[[command]]
trigger = ["matrix"]
response = "Our Matrix chat room: https://tinyurl.com/5n6zsmu5"

[[command]]
trigger = ["dotfiles", "editor", "shell", "theme"]
response = "All my setup and config can be found in my dotfiles: https://github.com/tombh/dotfiles"

[[command]]
trigger = ["github"]
response = "https://github.com/tombh"

[[command]]
trigger = ["project"]
response = "https://github.com/tombh/tattoy"

